maintenance: add upstream tracker RULE to TODO
canonical/ubuntu-mir pull request #5
Opened 2023-01-31 17:06 UTC by eslerm

A QA maintenance RULE requires the upstream's bug tracker to be checked for long-term & critical bugs, but that step is often skipped. This PR adds a TODO item to check upstream.

2023-02-07 15:59 UTC, slyon requested changes
Being maintained in a bug tracker sounds funny. But I like the pointer to check the upstream bug tracker!

2023-02-07 15:59 UTC, slyon commented on README.md
> +TODO:   and does not have too many, long-term & critical, open bugs
```suggestion
TODO: - The package is maintained well in Debian/Ubuntu/Upstream and does
TODO:   not have too many, long-term & critical, open bugs
```

2023-02-07 16:47 UTC, eslerm commented
thanks @slyon! that reads much better

2023-02-08 08:03 UTC, cpaelzer approved these changes

2023-02-08 08:03 UTC, cpaelzer commented
The suggestion of @slyon is added and together this will be helpful indeed, merging

2023-02-08 08:03 UTC, merged